config/routes.rb
Rbtorrent::Application.routes.draw do
  devise_for :users

  resources :torrents do
    resources :files, :controller => "torrent_file"

    member do
      post :start
      post :stop
      post :erase

    end

    collection do
      get :check
    end
  end

  root :to => "torrents#index"
end

app/models/torrent.rb
class Torrent
  MINIMUM_PROPERTIES = 
    [ :get_hash, :get_state, :get_ratio, :get_complete, 
      :is_open, :get_size_chunks, :get_completed_chunks, 
      :get_down_rate, :get_up_rate, :get_name,
      :get_size_files 
    ]

  OTHER_PROPERTIES = [ :get_down_total, :get_up_total, :get_chunk_size ]

  SPECIAL_METHODS = [ :get_up_rate, :get_down_rate ]

  STRING_PROPERTIES = [ :get_hash, :get_name ]
  
  def initialize(client, properties = {})
    puts properties.inspect
    @client = client
    raise ArgumentError, "Require get_hash property" unless (@hash = properties.delete(:get_hash))
    # quick start caches
    properties.each do |k,v|
      # puts "i: Setting @#{k} to #{v}"
      v = v.to_i unless STRING_PROPERTIES.include?(k)
      instance_variable_set "@#{k}", v
    end
  end

  private :initialize

  # State of the torrent; define a method that caches results but can force refresh them.
  (MINIMUM_PROPERTIES + OTHER_PROPERTIES - SPECIAL_METHODS).each do |m|
    attr_reader m
    ivar_name = "@#{m}".to_sym
    define_method(m, ->(force = false) do
      i = instance_variable_get ivar_name
      #	puts "m: #{ivar_name} set to: #{i}: VAR IS #{ i ? "SET" : "NOT" }"
      if i.nil? || force
        r = @client.call("d.#{m}", @hash)
        # puts "m: Setting #{ivar_name} to #{ r }"
        instance_variable_set ivar_name, r
      end
      instance_variable_get ivar_name
    end)
  end

  # Various manipulative actions
  [ :stop, :start, :erase ].each do |m|
    define_method m do
      @client.call "d.#{m}", get_hash
    end
  end

  # We want these to be proper values
  [ :get_up_rate, :get_down_rate ].each do |rate|
    define_method rate do
      found_rate = @client.call("d.#{rate}", get_hash).to_i
      (found_rate / 1024).round(4)
    end
  end

  public

  def get_hash
    @hash
  end

  def percentage
    return 0 if get_completed_chunks == 0
    (get_completed_chunks / get_size_chunks.to_f).round(4)
  end

  def get_status(force = false)
    # TODO: This should also check for messages.

    if is_open(force) != 1
      return "Closed"
    end

    active = (get_state(force) != 0)
    complete = (get_complete(force) != 0)

    if !active && !complete then
      "Started"
    elsif active && !complete
      "Downloading"
    elsif !active && complete
      "Finished"
    elsif active && complete
      "Seeding"
    end
  end

  # Get our multiple parts
  def files
    properties = [ :get_path ]
    index = 0
    @client.f.multicall( [get_hash, "0"], *properties ).map do |properties_hash|
      TorrentFile.new(@client, self, index, properties_hash).tap { index += 1 }
    end
  end

  def file(index)
    TorrentFile.new(@client, self, index)
  end

  def set_file_priorities(on_or_off)
    @client.f do
      get_size_files.times do |i|
        call "set_priority", get_hash, i, on_or_off[i.to_s] ? 1 : 0
      end
    end
  end

  class << self
    def all(client, args = {})
      view = args.delete(:view) || "default"

      properties = args.delete(:properties)
      properties ||= MINIMUM_PROPERTIES

      client.d.multicall(view, *properties).map do |properties_hash|
        self.new client, properties_hash
      end
    end

    def find(client, hash)
      puts "hi"
      self.new client, get_hash: hash
    end
  end
end

app/controllers/torrents_controller.rb
class TorrentsController < ApplicationController
  include RemoteFiles
  before_filter :authenticate_user!
  before_filter :create_connection

  def index
    @download_dir = ConfigOption.get "download-dir"
    
    @torrents = Torrent.all @connection
  end

  def new
  end

  def create
    url = params[:torrent][:url]
    start = params[:torrent][:start] == "0"
    torrent_dir = ConfigOption.get("torrent-dir").value

    contents, name = nil
    [
      [ lambda { contents = read_remote_file(url) }, "Could not read remote url!" ],
      [ lambda { name = write_local_file!(torrent_dir, contents) }, "Could not write local file!" ] 
    ].each do |f, error_message|
      unless f.call
        flash.alert = error_message
        render :action => :new
        return
      end
    end

    logger.debug "Here in the child..."

    @rtorrent = Rtorrent.new @connection

    logger.info "name,contents= #{[name,contents].inspect}"

    if @rtorrent.load torrent_dir, name, start
      flash.notice = "Successfully added torrent!"
    end

    render :action => :new
  end

  [ :start, :stop, :erase ].each do |action|
    define_method action do
      @torrent = Torrent.find @connection, params[:id]
      @torrent.send action

      render :partial => 'update'
    end
  end

  def check
    @torrents = Torrent.all @connection, :properties => [ :get_hash, :get_state, :get_ratio, 
                                                          :get_complete, :is_open, :get_size_chunks, 
                                                          :get_completed_chunks, :get_down_rate, 
                                                          :get_up_rate ]
    json_torrents = @torrents.map do |torrent|
      {}.tap do |h|
        [:hash, :status, :ratio, :down_rate, :up_rate].each do |property|
          h[property] = torrent.send "get_#{property}"
        end
        h[:percentage] = torrent.percentage
      end
    end
    render :json => json_torrents
  end

  private
  def create_connection
    @host = ConfigOption.get("host")
    @connection = Connection.new @host.value
  end
end

app/helpers/torrent_helper.rb
require 'shellwords'

module TorrentHelper
  def escape(string)
    Shellwords.shellescape(string)
  end
end

app/views/torrents/_clippy.html.haml
- scp = "scp -r narbsy.com:\'#{escape(clippy)}\' ~/Videos"
%span
  = scp
  %object{  :type => "application/x-shockwave-flash",
            :data => "/clippy.swf",
            :width => "110",
            :height => "14",
            :id => "clippy" }
    %param(name="movie" value="/clippy.swf")
    %param(name="FlashVars" value="text=#{scp}")

app/views/torrents/_update.js.haml
= "update_status('#{@torrent.get_hash}', '#{@torrent.get_status(true)}');"

app/views/torrents/index.html.haml
- status = 'finished'
- content_for :nav do
  %ul.right
    %li
      %a{ :href => "#", :onclick => "return show_all();" } All |
    - [ 'finished', 'started', 'downloading', 'seeding' ].each do |status|
      %li
        %a{ :href => "#", :onclick => "return hide_all_but('#{status}');" }= status.capitalize

%ul.torrents
  - @torrents.each do |torrent|
    %li{ :class => torrent.get_status.downcase, :id => "t" + torrent.get_hash }
      .title
        %span.name.large= torrent.get_name
        %span.status.right
          [
          = torrent.get_status
          ]

      .torrent
        %div.hash= torrent.get_hash
        %div
          %span.ratio
            Ratio:
            = (torrent.get_ratio / 1000.0).round(3)
          %span.rates.right
            Upload:
            = torrent.get_up_rate
            KB/s

            Download:
            = torrent.get_down_rate
            KB/s
        %div
          %div.percentage{ :style => "margin: auto" }
            = render :partial => "partials/percent_bar", :object => to_percent(torrent.percentage)
        %div.clear
          - [:stop, :start, :erase].each do |action|
            = link_to action.capitalize, send("#{action}_torrent_url", torrent.get_hash), :remote => true, :method => :post
          %span.on-top.right
            = render :partial => "clippy", :object => File.join(@download_dir.value, torrent.get_name)
            = link_to "<", "#", :onclick => "slide(event, '<', '>');"
        %div.clear
          Files
          = link_to "<", torrent_files_url(torrent.get_hash), :onclick => "slide(event, '<', 'V');", :remote => true
          %div.file-table{ :style => "display: none;" }
            = image_tag "ajax-loader.gif", :alt => "Loading..."

app/views/torrents/new.html.haml
= form_for "torrent", :url => torrents_path, :method => :post do |f|
  %p
    = f.label :url, "Add new torrent by url:"
    = f.text_field :url, :size => 255
  %p
    = f.label :start, "Start immediately?"
    = f.check_box :start

  = submit_tag "Add me!"