config/routes.rb
Rbtorrent::Application.routes.draw do
  devise_for :users

  resources :torrents do
    resources :files, :controller => "torrent_file"

    member do
      post :start
      post :stop
      post :erase

    end

    collection do
      get :check
    end
  end

  root :to => "torrents#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rbtorrent</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/default.html.haml
!!!
%html( xmlns="http://www.w3.org/1999/xhtml" )
  %head
    %meta(http-equiv="Content-type" content="text/html;charset=UTF-8")
    %title RbTorrent
    = csrf_meta_tag
    = stylesheet_link_tag "main.css"
    = javascript_include_tag "jquery-1.4.2.js", "rails.js", "idle-timer.js", "application.js"
  %body
    #header
      %h1.big
        %a{ :href => "/" } RbTorrent
      %h3.small.right.top rtorrent webgui built in Sinatra
      - if user_signed_in?
        .right.small.login
          Logged in as:
          = current_user.email
          = link_to "Logout", destroy_user_session_url
      - else
        .right.small.login
        = link_to "Log in", new_user_session_url
      .clear
      #nav
        = link_to "Add new torrent", new_torrent_path, :id => :add
        = yield :nav
    #notices
      .notice= notice
      .alert= alert
    .content
      = yield
    #footer
      $responsetime